print("dias de la semana:")
print("lunes")
print("martes")
print("miercoles")
print("jueves")
print("viernes")
print("sabado")
print("domingo")
print("")
print("meses del año:")
print("enero")
print("febrero")
print("marzo")
print("abril")
print("mayo")
print("junio")
print("julio")
print("agosto")
print("septiembre")
print("agosto")
print("octubre")
print("noviembre")
print("diciembre")
